default_stages: [commit]
exclude: ^(.github/|.venv/|.vscode/|.mypy_cache/)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      # - id: check-added-large-files

  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.16
    hooks:
      - id: circleci-config-validate

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        types: [python] # list of file types to run
        language: python # the language of the hook
        entry: poetry run flake8

      - id: black
        name: black
        types: [python]
        language: python
        entry: poetry run black

      - id: mypy
        name: mypy
        types: [python]
        language: python
        entry: poetry run mypy
        args: ["--pretty", "--follow-imports=silent"]

      - id: isort
        name: isort
        types: [python]
        language: python
        entry: poetry run isort
