version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2021.04

    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      - run:
          name: ghcr login
          command: |
            echo $CR_PAT | docker login $(echo $REGISTRY) -u $(echo $CR_USERNAME) --password-stdin

      - run:
          name: check docker compose version
          command: |
            docker-compose -v

      - run:
          name: build
          command: |
            docker-compose -f "./docker/docker-compose.yml" up -d --build

      - run:
          name: check containers
          command: |
            docker ps

      - run:
          name: shut down
          command: |
            docker-compose -f "./docker/docker-compose.yml" down

      - run:
          name: push to registry
          command: |
            docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):latest

      - run:
          name: final step
          command: |
            echo "FINISHED!"
