services:
  sieve:
    ports:
      - "5678:5678"
    entrypoint: ""
    command:
      - "sh"
      - "-c"
      - "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m sieve.__main__"
