services:
  sieve:
    container_name: sieve
    image: sieve:dev
    restart: unless-stopped
    env_file: ../.env
    tty: true
    networks:
      - sieve-network
    depends_on:
      - "db"
      - "browserless"
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: dev
    volumes:
      - "..:/sieve"

  db:
    container_name: postgres_db
    image: postgres:sieve
    restart: unless-stopped
    env_file: ../.env
    tty: true
    networks:
      - sieve-network
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.postgres
    volumes:
      - "postgres-db:/var/lib/postgresql/data"

  browserless:
    container_name: browserless
    image: browserless/chrome:latest
    restart: unless-stopped
    env_file: ../.env
    tty: true
    networks:
      - sieve-network
    ports:
      - "3000:3000"

volumes:
  postgres-db:
    name: sieve

networks:
  sieve-network:
    name: sieve
